version: "3.4"

services:
  webnotes-node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    tty: true
    container_name: webnotes-node
    ports:
      - "3000:3000"
    volumes:
      - ./:/var/www/app
    restart: unless-stopped
    depends_on:
      - webnotes-mysql
  webnotes-mysql:
    image: mysql:8
    container_name: webnotes-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
  webnotes-mailcatcher:
    image: schickling/mailcatcher
    container_name: webnotes-mailcatcher
    ports:
      - 1080:1080
    expose:
      - 1025